use crate::{
  errors::NovaError,
  spartan::{
    polys::{
      multilinear::MultilinearPolynomial,
      univariate::{CompressedUniPoly, UniPoly},
    },
    sumcheck::eq_sumcheck::EqSumCheckInstance,
  },
  traits::{Engine, TranscriptEngineTrait},
};
use ff::{Field, PrimeField};
use rayon::prelude::*;
use serde::{Deserialize, Serialize};

/// Defines a trait for implementing sum-check in a generic manner
pub trait SumcheckEngine<E: Engine>: Send + Sync {
  /// returns the initial claims
  fn initial_claims(&self) -> Vec<E::Scalar>;

  /// degree of the sum-check polynomial
  fn degree(&self) -> usize;

  /// the size of the polynomials
  fn size(&self) -> usize;

  /// Returns per-claim evaluation data for UniPoly interpolation.
  ///
  /// For degree-3 (cubic) claims: [p(0), cubic_coeff, p(-1)]
  /// For degree-2 (quadratic) claims: [p(0), 0, p(-1)]
  fn evaluation_points(&mut self) -> Vec<Vec<E::Scalar>>;

  /// bounds a variable in the constituent polynomials
  fn bound(&mut self, r: &E::Scalar);

  /// returns the final claims
  fn final_claims(&self) -> Vec<Vec<E::Scalar>>;
}

/// A proof generated by the sumcheck protocol.
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(bound = "")]
pub struct SumcheckProof<E: Engine> {
  compressed_polys: Vec<CompressedUniPoly<E::Scalar>>,
}

/// Per-table evaluation tuple returned by
/// [`SumcheckProof::prove_neutron_outer_with_logup`] (GH-#7 M.GH7.4a, Corrigendum #16).
///
/// Each field is the value of the corresponding per-table multilinear polynomial
/// at the outer-sumcheck challenge `r_x` (i.e., the polynomial bound through all
/// `ell = log2(num_cons)` rounds). The M.GH7.4b dispatch consumes the PCS-opened
/// subset `(eval_w, eval_ts, eval_inv_w, eval_inv_t)` as `PolyEvalInstance::e`
/// values when extending the batch-eval-reduce u_vec/w_vec; the remaining three
/// (`eval_T`, `eval_eq_w`, `eval_eq_t`) are NOT PCS-opened — `eval_T` is over
/// fixed table data (caller-reconstructed at verify), and the eq-factors are
/// verifier-reconstructed via `EqPolynomial::evaluate` against the eq-factor
/// challenges that defined them at construction time.
///
/// All seven polynomials are bound to length 1 after the outer sumcheck; the
/// engine reads `poly[0]` for each (mirroring how the R1CS-side
/// `(claim_Az, claim_Bz, claim_Cz)` are recovered at `sumcheck.rs:703-705`).
///
/// Embedded in [`crate::spartan::snark::RelaxedR1CSSNARK`] as the new
/// `per_table_outer_evals: Option<Vec<PerTableOuterEvals<E::Scalar>>>` field at
/// M.GH7.4b — the seven evals are part of the serialised proof envelope so the
/// verifier can reconstruct the outer-sumcheck unified residue claim per
/// Corrigendum #16 Finding B.
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(bound = "F: Serialize + serde::de::DeserializeOwned")]
#[allow(non_snake_case)]
pub struct PerTableOuterEvals<F: ff::PrimeField> {
  /// Value of the witness polynomial `w_j(r_x)`.
  pub eval_w: F,
  /// Value of the timestamp polynomial `ts_j(r_x)`.
  pub eval_ts: F,
  /// Value of the witness-side inverse polynomial `inv_w_j(r_x)`.
  pub eval_inv_w: F,
  /// Value of the table-side inverse polynomial `inv_t_j(r_x)`.
  pub eval_inv_t: F,
  /// Value of the table-data polynomial `T_j(r_x)`.
  pub eval_T: F,
  /// Value of the witness-side eq-factor `eq_w_j(r_x)`.
  pub eval_eq_w: F,
  /// Value of the table-side eq-factor `eq_t_j(r_x)`.
  pub eval_eq_t: F,
}

impl<E: Engine> SumcheckProof<E> {
  /// Creates a new `SumcheckProof` from compressed univariate polynomials.
  pub fn new(compressed_polys: Vec<CompressedUniPoly<E::Scalar>>) -> Self {
    Self { compressed_polys }
  }

  /// Returns reference to slice of compressed round polynomials.
  pub fn compressed_polys(&self) -> &[CompressedUniPoly<E::Scalar>] {
    &self.compressed_polys
  }

  /// Advance a running sumcheck claim after verifier challenge `r`.
  ///
  /// `evals` = `[p(0), cubic_coeff, p(-1)]` as returned by
  /// [`SumcheckEngine::evaluation_points`].  Works for both degree-3 (cubic)
  /// and degree-2 (quadratic, where `cubic_coeff = 0`) claims.
  ///
  /// Reconstructs the round polynomial from the BDDT evaluation points
  /// (eprint 2025/1117, Section 6.2) and evaluates it at `r` via Horner's
  /// method, all in O(1) without allocating.
  #[inline]
  pub fn update_claim(claim: E::Scalar, evals: &[E::Scalar; 3], r: &E::Scalar) -> E::Scalar {
    let [e0, c3, em1] = *evals;
    let e1 = claim - e0;
    let half = E::Scalar::TWO_INV;
    let a1 = (e1 - em1) * half - c3;
    let a2 = (e1 + em1) * half - e0;
    e0 + *r * (a1 + *r * (a2 + *r * c3))
  }

  /// Verifies the sumcheck proof.
  ///
  /// # Arguments
  /// * `claim` - The claimed sum
  /// * `num_rounds` - The number of sumcheck rounds
  /// * `degree_bound` - The degree bound of the univariate polynomials
  /// * `transcript` - The transcript for Fiat-Shamir
  ///
  /// # Returns
  /// A tuple of (final_evaluation, challenges) if verification succeeds.
  pub fn verify(
    &self,
    claim: E::Scalar,
    num_rounds: usize,
    degree_bound: usize,
    transcript: &mut E::TE,
  ) -> Result<(E::Scalar, Vec<E::Scalar>), NovaError> {
    let mut e = claim;
    let mut r: Vec<E::Scalar> = Vec::new();

    // verify that there is a univariate polynomial for each round
    if self.compressed_polys.len() != num_rounds {
      return Err(NovaError::InvalidSumcheckProof);
    }

    for i in 0..self.compressed_polys.len() {
      let poly = self.compressed_polys[i].decompress(&e);

      // verify degree bound
      if poly.degree() > degree_bound {
        return Err(NovaError::InvalidSumcheckProof);
      }

      // we do not need to check if poly(0) + poly(1) = e, as
      // decompress() call above already ensures that holds
      debug_assert_eq!(poly.eval_at_zero() + poly.eval_at_one(), e);

      // append the prover's message to the transcript
      transcript.absorb(b"p", &poly);

      //derive the verifier's challenge for the next round
      let r_i = transcript.squeeze(b"c")?;

      r.push(r_i);

      // evaluate the claimed degree-ell polynomial at r_i
      e = poly.evaluate(&r_i);
    }

    Ok((e, r))
  }

  /// Verifies a batch of sumcheck instances with different numbers of rounds.
  /// Claims are combined using random linear combination with the provided coefficients.
  pub fn verify_batch(
    &self,
    claims: &[E::Scalar],
    num_rounds: &[usize],
    coeffs: &[E::Scalar],
    degree_bound: usize,
    transcript: &mut E::TE,
  ) -> Result<(E::Scalar, Vec<E::Scalar>), NovaError> {
    let num_instances = claims.len();
    assert_eq!(num_rounds.len(), num_instances);
    assert_eq!(coeffs.len(), num_instances);

    // n = maxᵢ{nᵢ}
    let num_rounds_max = *num_rounds.iter().max().unwrap();

    // Random linear combination of claims,
    // where each claim is scaled by 2^{n-nᵢ} to account for the padding.
    //
    // claim = ∑ᵢ coeffᵢ⋅2^{n-nᵢ}⋅cᵢ
    let claim = claims
      .iter()
      .zip(num_rounds.iter())
      .zip(coeffs.iter())
      .map(|((claim, &nr), coeff)| {
        let scale = E::Scalar::from(2u64).pow_vartime([(num_rounds_max - nr) as u64]);
        *claim * scale * coeff
      })
      .sum();

    self.verify(claim, num_rounds_max, degree_bound, transcript)
  }

  // comb_func: |p, q| p * q
  #[inline]
  fn compute_eval_points_quad_prod(
    poly_A: &MultilinearPolynomial<E::Scalar>,
    poly_B: &MultilinearPolynomial<E::Scalar>,
  ) -> (E::Scalar, E::Scalar) {
    let len = poly_A.len() / 2;
    (0..len)
      .into_par_iter()
      .map(|i| {
        // eval 0: bound_func is A(low)
        let eval_point_0 = poly_A[i] * poly_B[i];

        // eval quadratic coefficient: (A(high)-A(low)) * (B(high)-B(low))
        let poly_A_bound_coeff = poly_A[len + i] - poly_A[i];
        let poly_B_bound_coeff = poly_B[len + i] - poly_B[i];
        let bound_coeff = poly_A_bound_coeff * poly_B_bound_coeff;
        (eval_point_0, bound_coeff)
      })
      .reduce(
        || (E::Scalar::ZERO, E::Scalar::ZERO),
        |a, b| (a.0 + b.0, a.1 + b.1),
      )
  }

  /// Proves a sumcheck for `sum_x poly_A(x) * poly_B(x)`.
  ///
  /// # Arguments
  /// * `claim` - The claimed sum
  /// * `num_rounds` - The number of sumcheck rounds
  /// * `poly_A` - First multilinear polynomial (will be mutated)
  /// * `poly_B` - Second multilinear polynomial (will be mutated)
  /// * `transcript` - The transcript for Fiat-Shamir
  ///
  /// # Returns
  /// A tuple of (proof, challenges, final_evaluations).
  pub fn prove_quad_prod(
    claim: &E::Scalar,
    num_rounds: usize,
    poly_A: &mut MultilinearPolynomial<E::Scalar>,
    poly_B: &mut MultilinearPolynomial<E::Scalar>,
    transcript: &mut E::TE,
  ) -> Result<(Self, Vec<E::Scalar>, Vec<E::Scalar>), NovaError> {
    let mut r: Vec<E::Scalar> = Vec::new();
    let mut polys: Vec<CompressedUniPoly<E::Scalar>> = Vec::new();
    let mut claim_per_round = *claim;
    for _ in 0..num_rounds {
      let poly = {
        let (eval_point_0, bound_coeff) = Self::compute_eval_points_quad_prod(poly_A, poly_B);

        let evals = vec![eval_point_0, claim_per_round - eval_point_0, bound_coeff];
        UniPoly::from_evals_deg2(&evals)
      };

      // append the prover's message to the transcript
      transcript.absorb(b"p", &poly);

      //derive the verifier's challenge for the next round
      let r_i = transcript.squeeze(b"c")?;
      r.push(r_i);
      polys.push(poly.compress());

      // Set up next round
      claim_per_round = poly.evaluate(&r_i);

      // bind all tables to the verifier's challenge
      rayon::join(
        || poly_A.bind_poly_var_top(&r_i),
        || poly_B.bind_poly_var_top(&r_i),
      );
    }

    Ok((
      SumcheckProof {
        compressed_polys: polys,
      },
      r,
      vec![poly_A[0], poly_B[0]],
    ))
  }

  /// Batched sumcheck for polynomial evaluation claims.
  ///
  /// Each instance `i` proves `e_i = sum_x P_i(x) * eq(x_i, x)` over `{0,1}^{n_i}`,
  /// where `P_i` is a witness polynomial and `x_i` is the evaluation point.
  /// Uses `EqSumCheckInstance` to avoid materializing the eq tables.
  ///
  /// Returns `(proof, challenges, P_i_final_evals)`.
  pub fn prove_batch_eval(
    claims: &[E::Scalar],
    num_rounds: &[usize],
    mut polys: Vec<MultilinearPolynomial<E::Scalar>>,
    eq_points: Vec<Vec<E::Scalar>>,
    coeffs: &[E::Scalar],
    transcript: &mut E::TE,
  ) -> Result<(Self, Vec<E::Scalar>, Vec<E::Scalar>), NovaError> {
    let num_claims = claims.len();

    assert_eq!(num_rounds.len(), num_claims);
    assert_eq!(polys.len(), num_claims);
    assert_eq!(eq_points.len(), num_claims);
    assert_eq!(coeffs.len(), num_claims);

    for (i, &nr) in num_rounds.iter().enumerate() {
      assert_eq!(polys[i].len(), 1 << nr, "poly size mismatch at index {i}");
      assert_eq!(
        eq_points[i].len(),
        nr,
        "eq_point length mismatch at index {i}"
      );
    }

    let num_rounds_max = *num_rounds.iter().max().unwrap();

    let mut eq_instances: Vec<EqSumCheckInstance<E>> =
      eq_points.into_iter().map(EqSumCheckInstance::new).collect();

    let mut running_claims: Vec<E::Scalar> = claims.to_vec();

    let mut e: E::Scalar = claims
      .iter()
      .zip(num_rounds.iter())
      .zip(coeffs.iter())
      .map(|((claim, &nr), coeff)| {
        let scale = E::Scalar::from(2u64).pow_vartime([(num_rounds_max - nr) as u64]);
        *claim * scale * coeff
      })
      .sum();

    let mut r: Vec<E::Scalar> = Vec::new();
    let mut quad_polys: Vec<CompressedUniPoly<E::Scalar>> = Vec::new();

    for current_round in 0..num_rounds_max {
      let remaining_rounds = num_rounds_max - current_round;

      // Per-claim [S_i(0), 0, S_i(-1)] for `update_claim` (c3=0 since P*eq is degree 2)
      let evals: Vec<[E::Scalar; 3]> = (0..num_claims)
        .into_par_iter()
        .map(|i| {
          if remaining_rounds <= num_rounds[i] {
            let (eval_0, _cubic_coeff, eval_m1) = eq_instances[i]
              .evaluation_points_quadratic_with_one_input(&polys[i], running_claims[i]);
            [eval_0, E::Scalar::ZERO, eval_m1]
          } else {
            // not yet started: constant (replicated)
            let remaining_variables = remaining_rounds - num_rounds[i] - 1;
            let scaled_claim =
              E::Scalar::from(2u64).pow_vartime([remaining_variables as u64]) * claims[i];
            [scaled_claim, E::Scalar::ZERO, scaled_claim]
          }
        })
        .collect();

      let evals_combined_0: E::Scalar = (0..num_claims).map(|i| evals[i][0] * coeffs[i]).sum();
      let evals_combined_m1: E::Scalar = (0..num_claims).map(|i| evals[i][2] * coeffs[i]).sum();

      // quadratic coeff: a = (S(1) + S(-1) - 2*S(0)) / 2
      let evals_combined_1 = e - evals_combined_0;
      let quad_coeff =
        (evals_combined_1 + evals_combined_m1 - evals_combined_0.double()) * E::Scalar::TWO_INV;

      let uni_evals = vec![evals_combined_0, evals_combined_1, quad_coeff];
      let poly = UniPoly::from_evals_deg2(&uni_evals);

      // append the prover's message to the transcript
      transcript.absorb(b"p", &poly);

      // derive the verifier's challenge for the next round
      let r_i = transcript.squeeze(b"c")?;
      r.push(r_i);

      for i in 0..num_claims {
        if remaining_rounds <= num_rounds[i] {
          running_claims[i] = Self::update_claim(running_claims[i], &evals[i], &r_i);
          polys[i].bind_poly_var_top(&r_i);
          eq_instances[i].bound(&r_i);
        }
      }

      e = poly.evaluate(&r_i);
      quad_polys.push(poly.compress());
    }

    polys.iter().for_each(|p| assert_eq!(p.len(), 1));

    let poly_finals: Vec<E::Scalar> = polys.into_iter().map(|poly| poly[0]).collect();

    Ok((SumcheckProof::new(quad_polys), r, poly_finals))
  }

  /// Computes evaluation points for a linear sumcheck round (poly_A - poly_B).
  /// Returns (eval_0, eval_inf) since the bound coefficient is always 0 for linear.
  #[inline]
  pub fn compute_eval_points_linear(
    poly_A: &MultilinearPolynomial<E::Scalar>,
    poly_B: &MultilinearPolynomial<E::Scalar>,
  ) -> (E::Scalar, E::Scalar) {
    let len = poly_A.len() / 2;
    (0..len)
      .into_par_iter()
      .map(|i| {
        // eval 0: A(low) - B(low)
        let eval_point_0 = poly_A[i] - poly_B[i];

        // eval -1: A(-1) - B(-1)
        // A(-1) = A(low) - (A(high) - A(low)) = 2*A(low) - A(high)
        let poly_A_inf_point = poly_A[i] + poly_A[i] - poly_A[len + i];
        let poly_B_inf_point = poly_B[i] + poly_B[i] - poly_B[len + i];
        let eval_point_inf = poly_A_inf_point - poly_B_inf_point;

        (eval_point_0, eval_point_inf)
      })
      .reduce(
        || (E::Scalar::ZERO, E::Scalar::ZERO),
        |a, b| (a.0 + b.0, a.1 + b.1),
      )
  }

  /// Computes evaluation points for a quadratic sumcheck round (poly_A * poly_B).
  /// Returns (eval_0, eval_inf) since the bound coefficient is always 0 for quadratic.
  #[inline]
  pub fn compute_eval_points_quadratic(
    poly_A: &MultilinearPolynomial<E::Scalar>,
    poly_B: &MultilinearPolynomial<E::Scalar>,
  ) -> (E::Scalar, E::Scalar) {
    let len = poly_A.len() / 2;
    (0..len)
      .into_par_iter()
      .map(|i| {
        // eval 0: A(low) * B(low)
        let eval_point_0 = poly_A[i] * poly_B[i];

        // eval -1: A(-1) * B(-1)
        // A(-1) = A(low) - (A(high) - A(low)) = 2*A(low) - A(high)
        let poly_A_inf_point = poly_A[i] + poly_A[i] - poly_A[len + i];
        let poly_B_inf_point = poly_B[i] + poly_B[i] - poly_B[len + i];
        let eval_point_inf = poly_A_inf_point * poly_B_inf_point;

        (eval_point_0, eval_point_inf)
      })
      .reduce(
        || (E::Scalar::ZERO, E::Scalar::ZERO),
        |a, b| (a.0 + b.0, a.1 + b.1),
      )
  }

  /// Computes evaluation points for a cubic product sumcheck round (`poly_A * poly_B * poly_C`).
  ///
  /// Returns `(eval_0, cubic_coeff, eval_inf)` where:
  /// - `eval_0 = sum A_lo * B_lo * C_lo`
  /// - `cubic_coeff = sum dA * dB * dC`
  /// - `eval_inf = sum A(-1) * B(-1) * C(-1)`
  #[inline]
  pub fn compute_eval_points_cubic(
    poly_A: &MultilinearPolynomial<E::Scalar>,
    poly_B: &MultilinearPolynomial<E::Scalar>,
    poly_C: &MultilinearPolynomial<E::Scalar>,
  ) -> (E::Scalar, E::Scalar, E::Scalar) {
    let len = poly_A.len() / 2;
    (0..len)
      .into_par_iter()
      .map(|i| {
        // eval 0: A(low) * B(low) * C(low)
        let eval_point_0 = poly_A[i] * poly_B[i] * poly_C[i];

        // cubic coefficient: dA * dB * dC
        let d_a = poly_A[len + i] - poly_A[i];
        let d_b = poly_B[len + i] - poly_B[i];
        let d_c = poly_C[len + i] - poly_C[i];
        let cubic_coeff = d_a * d_b * d_c;

        // eval -1: A(-1) * B(-1) * C(-1)
        let eval_point_inf = (poly_A[i] - d_a) * (poly_B[i] - d_b) * (poly_C[i] - d_c);

        (eval_point_0, cubic_coeff, eval_point_inf)
      })
      .reduce(
        || (E::Scalar::ZERO, E::Scalar::ZERO, E::Scalar::ZERO),
        |a, b| (a.0 + b.0, a.1 + b.1, a.2 + b.2),
      )
  }

  /// Prove poly_A * poly_B - poly_C
  pub fn prove_cubic_with_three_inputs(
    claim: &E::Scalar,
    taus: Vec<E::Scalar>,
    poly_A: &mut MultilinearPolynomial<E::Scalar>,
    poly_B: &mut MultilinearPolynomial<E::Scalar>,
    poly_C: &mut MultilinearPolynomial<E::Scalar>,
    transcript: &mut E::TE,
  ) -> Result<(Self, Vec<E::Scalar>, Vec<E::Scalar>), NovaError> {
    let mut r: Vec<E::Scalar> = Vec::new();
    let mut polys: Vec<CompressedUniPoly<E::Scalar>> = Vec::new();
    let mut claim_per_round = *claim;

    let num_rounds = taus.len();

    let mut eq_instance = EqSumCheckInstance::<E>::new(taus);

    for _ in 0..num_rounds {
      let poly = {
        // Compute eval points using only 2 N-scaling sums (BDDT, eprint 2025/1117 Section 6.2)
        let (eval_point_0, eval_point_bound_coeff, eval_point_inf) = eq_instance
          .evaluation_points_cubic_with_three_inputs(poly_A, poly_B, poly_C, claim_per_round);

        let evals = vec![
          eval_point_0,
          claim_per_round - eval_point_0,
          eval_point_bound_coeff,
          eval_point_inf,
        ];

        UniPoly::from_evals_deg3(&evals)
      };

      // append the prover's message to the transcript
      transcript.absorb(b"p", &poly);

      //derive the verifier's challenge for the next round
      let r_i = transcript.squeeze(b"c")?;
      r.push(r_i);
      polys.push(poly.compress());

      // Set up next round
      claim_per_round = poly.evaluate(&r_i);

      // bound all tables to the verifier's challenge
      rayon::join(
        || poly_A.bind_poly_var_top(&r_i),
        || poly_B.bind_poly_var_top(&r_i),
      );
      rayon::join(
        || poly_C.bind_poly_var_top(&r_i),
        || eq_instance.bound(&r_i),
      );
    }

    Ok((
      SumcheckProof {
        compressed_polys: polys,
      },
      r,
      vec![poly_A[0], poly_B[0], poly_C[0]],
    ))
  }

  // ---------------------------------------------------------------------------
  // M.GH7.0.0b — Spartan neutron-outer sumcheck engine (Corrigendum #10)
  //
  // Proves the *neutron-form* claim
  //   sum_x full_E(x) · (Az(x) · Bz(x) − Cz(x)) = claim
  // where `full_E[i*left + j] = E2[i] · E1[j]` per Corrigendum #9 (2-A) layout
  // (matching `vendor/nova/src/neutron/lookup_sumcheck.rs:308-322` byte-for-byte).
  //
  // Structurally mirrors `prove_cubic_with_three_inputs` above:
  //   - degree-3 univariate per round
  //   - `bind_poly_var_top(&r_i)` per round (TOP/MSB first)
  //   - claim-per-round accumulator (initialised to the prover's `claim`)
  //
  // Two divergences from `prove_cubic_with_three_inputs`:
  //   (i) weighting polynomial: tensor-form `full_E = E1 ⊗ E2` instead of the
  //       `EqSumCheckInstance::<E>::new(taus)` built from fresh `tau` squeezes.
  //       Vendor-grounded by `lookup_sumcheck.rs:46-55` `LookupSumcheckInstance::
  //       verify_step` at the fold-step granularity analogue (tensor `eq_left ·
  //       eq_right` weighting with non-zero running claim).
  //   (ii) residue body: degree-3 `A · B − C` (NO `u`-factor on Cz — Δ2
  //        absorbed structurally; the slack lives in T).
  //
  // Per Corrigendum #9 (3-A) precedent (already used in `prove_with_split_error`
  // at M.GH7.0.0), the engine materialises `full_E` once at the start as a flat
  // `MultilinearPolynomial<E::Scalar>` of length `left * right = 2^ell`, then
  // runs the per-round binding against the flat polynomial. The tensor-form
  // factorisation is enforced ONLY at the verifier (which reconstructs
  // `eval_E_combined = eval_E1 · eval_E2` from independently-PCS-opened
  // evaluations `eval_E1 = E1_MLE(r_x_low)` and `eval_E2 = E2_MLE(r_x_high)`).
  //
  // Returns `(proof, r_x, (claim_Az, claim_Bz, claim_Cz, eval_E1, eval_E2))`
  // — five-tuple of final evaluations the Spartan-close sibling needs to
  // reconstruct `claim_outer_final` and absorb into the post-outer-sumcheck
  // transcript.
  // ---------------------------------------------------------------------------
  /// Prove `sum_x full_E(x) · (Az(x) · Bz(x) − Cz(x)) = claim`, where
  /// `full_E = E1 ⊗ E2` is the rank-1 tensor product weighting per Corrigendum
  /// #9 (2-A) layout `full_E[i*left + j] = E2[i] · E1[j]`. Non-zero claims
  /// supported (the running neutron-form claim `T` from the IVC layer).
  ///
  /// See module-level documentation for the soundness anchor (Primitives 1, 2)
  /// and the structural divergence from `prove_cubic_with_three_inputs`.
  #[allow(non_snake_case)]
  pub fn prove_neutron_outer(
    claim: E::Scalar,
    E1: &[E::Scalar],
    E2: &[E::Scalar],
    poly_Az: &mut MultilinearPolynomial<E::Scalar>,
    poly_Bz: &mut MultilinearPolynomial<E::Scalar>,
    poly_Cz: &mut MultilinearPolynomial<E::Scalar>,
    transcript: &mut E::TE,
  ) -> Result<
    (
      Self,
      Vec<E::Scalar>,
      (E::Scalar, E::Scalar, E::Scalar, E::Scalar, E::Scalar),
    ),
    NovaError,
  > {
    let left = E1.len();
    let right = E2.len();
    let num_rounds_total = poly_Az.len().trailing_zeros() as usize;
    assert_eq!(
      left * right,
      poly_Az.len(),
      "prove_neutron_outer: left*right must equal poly_Az.len() (== num_cons)",
    );
    assert_eq!(poly_Az.len(), poly_Bz.len());
    assert_eq!(poly_Az.len(), poly_Cz.len());
    assert!(left.is_power_of_two() && right.is_power_of_two());

    // Corrigendum #9 (3-A): materialise `full_E[i*left + j] = E2[i] · E1[j]`
    // once at the start of the engine. Sumcheck runs UNCHANGED against this
    // flat polynomial — the rank-1 factorisation is enforced ONLY at the
    // verifier. Memory cost: `num_cons * 32` bytes parallel to existing
    // Az/Bz/Cz allocations.
    let mut poly_E: MultilinearPolynomial<E::Scalar> = {
      let mut full_E: Vec<E::Scalar> = Vec::with_capacity(left * right);
      for i in 0..right {
        for j in 0..left {
          full_E.push(E2[i] * E1[j]);
        }
      }
      debug_assert_eq!(full_E.len(), left * right);
      MultilinearPolynomial::new(full_E)
    };

    // For determinism vs the M.GH7.0.0 binding direction: bind_poly_var_top
    // binds the TOP (MSB) variable first. Round 0 binds the MSB; under the
    // flat layout `k = i*left + j` (Corrigendum #9 (2-A)), the TOP ell2 bits
    // are `i ∈ [0, right)` (E2's outer index). After ell2 rounds, E2's index
    // is bound; the remaining ell1 rounds bind E1's inner index `j`. The
    // accumulated `r_x` therefore partitions as
    //   r_x_high = r_x[..ell2] (top, binds E2),
    //   r_x_low  = r_x[ell2..] (bottom, binds E1).
    // The Spartan-close sibling consumes this partition convention verbatim.

    let mut r: Vec<E::Scalar> = Vec::with_capacity(num_rounds_total);
    let mut polys: Vec<CompressedUniPoly<E::Scalar>> = Vec::with_capacity(num_rounds_total);
    let mut claim_per_round = claim;

    for _round in 0..num_rounds_total {
      // Compute the per-round univariate `g_round(t)` of degree 3:
      //   g_round(t) = sum_{x∈{0,1}^remaining} E(t,x) · (A(t,x)·B(t,x) − C(t,x))
      // After the top variable is bound to `t`, each multilinear `P ∈ {E, A, B, C}`
      // is linear in `t`:
      //   P(t, x) = P_lo[x] + t · (P_hi[x] − P_lo[x])  =  P_lo[x] + t · dP[x]
      // The body has degree 3 in `t` (E is degree-1, A·B − C is degree-2;
      // product is degree-3).
      //
      // We evaluate `g_round` at 4 points {0, 1, ∞, −1} to interpolate via
      // `UniPoly::from_evals_deg3`. Per BDDT-style claim derivation
      // (used by `prove_cubic_with_three_inputs` above), the value at t=1 is
      // derived from the running claim: `g_round(1) = claim_per_round − g_round(0)`.
      // We compute 3 N-scaling sums directly: eval_at_0, leading_coeff (eval@∞),
      // and eval_at_minus_one.
      let (eval_0, leading_coeff, eval_neg1) = {
        let n = poly_Az.len() / 2;
        debug_assert_eq!(n, poly_E.len() / 2);

        (0..n)
          .into_par_iter()
          .map(|i| {
            let a_lo = poly_Az[i];
            let b_lo = poly_Bz[i];
            let c_lo = poly_Cz[i];
            let e_lo = poly_E[i];

            let a_hi = poly_Az[n + i];
            let b_hi = poly_Bz[n + i];
            let c_hi = poly_Cz[n + i];
            let e_hi = poly_E[n + i];

            // g(0) = E_lo · (A_lo · B_lo − C_lo)
            let g0 = e_lo * (a_lo * b_lo - c_lo);

            // Leading coefficient (= g(∞)): coefficient of t^3 in
            //   (e_lo + t·dE) · ((a_lo + t·dA)(b_lo + t·dB) − (c_lo + t·dC))
            // The Cz part contributes 0 to t^3 (it's only degree 1 in t,
            // multiplied by E gives degree 2). The A·B·E part contributes
            // `dE · dA · dB` to t^3.
            let d_a = a_hi - a_lo;
            let d_b = b_hi - b_lo;
            let d_e = e_hi - e_lo;
            let leading = d_e * d_a * d_b;

            // g(−1): each polynomial at t=−1: P(−1) = P_lo − dP = 2·P_lo − P_hi.
            let a_m1 = a_lo + a_lo - a_hi;
            let b_m1 = b_lo + b_lo - b_hi;
            let c_m1 = c_lo + c_lo - c_hi;
            let e_m1 = e_lo + e_lo - e_hi;
            let g_m1 = e_m1 * (a_m1 * b_m1 - c_m1);

            (g0, leading, g_m1)
          })
          .reduce(
            || (E::Scalar::ZERO, E::Scalar::ZERO, E::Scalar::ZERO),
            |a, b| (a.0 + b.0, a.1 + b.1, a.2 + b.2),
          )
      };

      // g(1) = claim_per_round − g(0) (claim-derivation hint).
      let evals = vec![
        eval_0,
        claim_per_round - eval_0,
        leading_coeff,
        eval_neg1,
      ];
      let poly = UniPoly::from_evals_deg3(&evals);

      // append the prover's message to the transcript
      transcript.absorb(b"p", &poly);

      // derive the verifier's challenge for the next round
      let r_i = transcript.squeeze(b"c")?;
      r.push(r_i);
      polys.push(poly.compress());

      // Set up next round: claim_per_round ← g(r_i)
      claim_per_round = poly.evaluate(&r_i);

      // Bind all four polynomials at the top variable.
      rayon::join(
        || poly_Az.bind_poly_var_top(&r_i),
        || poly_Bz.bind_poly_var_top(&r_i),
      );
      rayon::join(
        || poly_Cz.bind_poly_var_top(&r_i),
        || poly_E.bind_poly_var_top(&r_i),
      );
    }

    // After `num_rounds_total = ell` rounds, all four polynomials are reduced
    // to a single scalar each.
    let claim_Az = poly_Az[0];
    let claim_Bz = poly_Bz[0];
    let claim_Cz = poly_Cz[0];

    // Reconstruct the tensor-form factorisation at the verifier's evaluation
    // point. Per Corrigendum #9 (2-A): r_x_high = r[..ell2] (binds E2);
    // r_x_low = r[ell2..] (binds E1). We do not need ell1/ell2 inside the
    // engine — left.log_2() and right.log_2() recover them.
    let ell2 = right.trailing_zeros() as usize;
    let r_x_high = &r[..ell2];
    let r_x_low = &r[ell2..];

    let eval_E1 = MultilinearPolynomial::new(E1.to_vec()).evaluate(r_x_low);
    let eval_E2 = MultilinearPolynomial::new(E2.to_vec()).evaluate(r_x_high);

    // Soundness consistency check (debug-only): the flat reduction matches the
    // tensor reconstruction. This is the Primitive 2 byte-equivalence at the
    // single evaluation point that the M.GH7.0.0b weighting differential
    // already covers across 1000-iter RNG sweeps. Kept as `debug_assert!` so
    // release-mode parity tests are not slowed.
    debug_assert_eq!(
      poly_E[0],
      eval_E1 * eval_E2,
      "Corrigendum #9 (2-A) tensor factorisation byte-divergence at end of \
       outer-sumcheck — Falsifier D"
    );

    Ok((
      SumcheckProof {
        compressed_polys: polys,
      },
      r,
      (claim_Az, claim_Bz, claim_Cz, eval_E1, eval_E2),
    ))
  }

  // ---------------------------------------------------------------------------
  // GH-#7 M.GH7.4a (Corrigendum #16) — Spartan-close outer-sumcheck SIBLING with
  // per-table LogUp (A)+(B) residue composition.
  //
  // Algebra (Corrigendum #16 Finding B + Finding C):
  //
  //   Outer claim:
  //     T = sum_x [ full_E(x) · (Az(x)·Bz(x) − Cz(x))
  //              + Σ_j eq_w_j(x) · (inv_w_j(x)·(w_j(x) + r_logup_j) − 1)
  //              + Σ_j eq_t_j(x) · (inv_t_j(x)·(T_j(x) + r_logup_j) − ts_j(x))  ]
  //
  //   On honestly-constructed LogUp inputs (`inv_w_j[i] = 1/(w_j[i] + r_logup_j)`,
  //   `inv_t_j[i] = ts_j[i]/(T_j[i] + r_logup_j)`), each (A) and (B) summand is
  //   identically zero (the inner factor vanishes pointwise on the hypercube), so
  //   the running claim collapses to the R1CS-side `T` carried in from
  //   `FoldedInstance::T` — the per-table additive contribution is zero by the
  //   honest-LogUp construction (see Haböck eprint 2022/1530 §3 (A)+(B) identities;
  //   `vendor/nova/src/neutron/lookup_sumcheck.rs:240-243` documents the same
  //   pointwise-zero collapse at fold-step granularity).
  //
  //   Per-round degree (Finding C disposition: degree-3 under additive composition):
  //     - R1CS-side body:     eq_w-factor=full_E·(Az·Bz − Cz) is degree-3 in `t`
  //       (full_E degree-1, Az·Bz degree-2, Cz degree-1 — degree-1×degree-2 = 3).
  //     - (A) per-table body: eq_w_j(t)·(inv_w_j(t)·(w_j(t) + r) − 1) is degree-3
  //       (eq_w_j degree-1; inv_w_j·(w_j+r) degree-2; minus 1 is degree-2;
  //       degree-1×degree-2 = degree-3).
  //     - (B) per-table body: eq_t_j(t)·(inv_t_j(t)·(T_j(t) + r) − ts_j(t)) is
  //       degree-3 (symmetric to (A); subtracting a degree-1 from a degree-2 is
  //       still degree-2; degree-1×degree-2 = degree-3).
  //     - Additive composition of degree-3 terms is degree-3.
  //
  //   Per-round evaluation point set `{0, 1, ∞, −1}` (same 4 points as
  //   `prove_neutron_outer`); `g(1) = claim_per_round − g(0)` reconstructed via
  //   the BDDT-style sumcheck claim hint.
  //
  //   Per-table variable partition (Finding F disposition): the caller passes
  //   per-table polynomials `(w_j, ts_j, inv_w_j, inv_t_j, T_j)` and per-table
  //   eq-factors `(eq_w_j, eq_t_j)` PRE-FLATTENED onto the R1CS variable space at
  //   length `num_cons = left * right`. Per-round binding via
  //   `bind_poly_var_top` applies in parallel to ALL polynomials (R1CS-side AND
  //   per-table) — the Corrigendum #9 (2-A) `r_x_high`/`r_x_low` partition is
  //   preserved verbatim for the R1CS-side `full_E` factorisation; per-table
  //   polys are additive residue terms and do NOT factor through E1/E2.
  //
  //   (C)-identity per table reduces to a per-table inner-sumcheck batched-eval
  //   claim per Corrigendum #16 Finding B. NOT closed by this method — closed
  //   at M.GH7.4b via the extended `batch_eval_reduce` machinery.
  //
  // Returns (proof, r_x, claims_outer_with_logup) where
  //   claims_outer_with_logup = (
  //     claim_Az, claim_Bz, claim_Cz, eval_E1, eval_E2,
  //     per_table_outer_evals: Vec<PerTableOuterEvals>,
  //   )
  // and `PerTableOuterEvals { eval_w_j, eval_ts_j, eval_inv_w_j, eval_inv_t_j,
  // eval_T_j, eval_eq_w_j, eval_eq_t_j }` is the post-binding value of each
  // per-table polynomial at `r_x`. These per-table evals are the inputs the
  // M.GH7.4b dispatch wires into `batch_eval_reduce` for PCS-opening; M.GH7.4a
  // returns them but does not consume them at the Spartan-side batch.
  //
  // STOP-AND-ASK disposition (Corrigendum #16 §5.5 row M.GH7.4a):
  //   Gate #1 (sibling vs extend-in-place): SIBLING — `prove_neutron_outer` at
  //     `sumcheck.rs:552-737` is preserved verbatim, M.GH7.0.0b STAGE-0
  //     byte-equivalence guaranteed.
  //   Gate #2 (degree-3 empirical close): algebra-verified at degree-3 above;
  //     empirically closed by the M.GH7.4a acceptance test below
  //     (`m_gh7_4a_prove_neutron_outer_with_logup_degree_3_additive_composition_closes_correctly`).
  //   Gate #3 (per-table variable partition): resolved via flat embedding
  //     onto R1CS variable space (length `num_cons` per per-table poly); caller
  //     at M.GH7.4c performs the lift; per-round binding applies uniformly via
  //     `bind_poly_var_top`. Corrigendum #9 (2-A) partition preserved verbatim.
  // ---------------------------------------------------------------------------

  /// Prove the M.GH7.4 unified outer-sumcheck claim
  ///   `sum_x g(x) = claim`
  /// where
  ///   `g(x) = full_E(x)·(Az(x)·Bz(x) − Cz(x))
  ///         + Σ_j eq_w_j(x)·(inv_w_j(x)·(w_j(x) + r_logup_j) − 1)
  ///         + Σ_j eq_t_j(x)·(inv_t_j(x)·(T_j(x) + r_logup_j) − ts_j(x))`
  /// under simple additive composition per Corrigendum #16 Finding B (no gamma-RLC).
  ///
  /// See module-level documentation above for the soundness anchor and the
  /// per-round degree-3 derivation under additive composition. See `sumcheck.rs`
  /// module documentation for the engine-level primitives.
  ///
  /// ## Inputs
  ///
  /// - `claim`: the running unified outer-sumcheck claim `T` (R1CS-side T;
  ///   per-table contribution is zero on honest LogUp inputs by construction).
  /// - `(E1, E2)`: R1CS-side rank-1 tensor factors of length `left`, `right`
  ///   per Corrigendum #9 (2-A).
  /// - `(poly_Az, poly_Bz, poly_Cz)`: R1CS-side MLEs of length `num_cons = left*right`.
  /// - `per_table_eq_w[j]`, `per_table_eq_t[j]`: per-table eq-factors pre-flattened
  ///   onto the R1CS variable space, length `num_cons` each (Finding F disposition).
  /// - `per_table_inv_w[j]`, `per_table_inv_t[j]`, `per_table_w[j]`,
  ///   `per_table_ts[j]`, `per_table_T[j]`: per-table polynomial data
  ///   pre-flattened onto the R1CS variable space, length `num_cons` each.
  /// - `r_logup_per_table[j]`: per-table LogUp challenge, squeezed at envelope-side
  ///   BEFORE the Spartan-close transcript begins (preserving Corrigendum #11
  ///   envelope-Spartan FS isolation — per-table `r_logup_j` are scalar inputs
  ///   here, NOT transcript squeezes).
  /// - `transcript`: the Spartan-close FS transcript (already absorbed `vk`, `U`,
  ///   `T_claim` per Corrigendum #10 §1.2(a) discipline).
  ///
  /// ## Output
  ///
  /// `(proof, r_x, (claim_Az, claim_Bz, claim_Cz, eval_E1, eval_E2,
  ///   per_table_outer_evals))` where `per_table_outer_evals[j]` is a
  /// `PerTableOuterEvals` carrying the seven per-table polynomial values at `r_x`.
  #[allow(clippy::too_many_arguments)]
  #[allow(non_snake_case)]
  pub fn prove_neutron_outer_with_logup(
    claim: E::Scalar,
    E1: &[E::Scalar],
    E2: &[E::Scalar],
    poly_Az: &mut MultilinearPolynomial<E::Scalar>,
    poly_Bz: &mut MultilinearPolynomial<E::Scalar>,
    poly_Cz: &mut MultilinearPolynomial<E::Scalar>,
    per_table_eq_w: &[Vec<E::Scalar>],
    per_table_eq_t: &[Vec<E::Scalar>],
    per_table_inv_w: &[Vec<E::Scalar>],
    per_table_inv_t: &[Vec<E::Scalar>],
    per_table_w: &[Vec<E::Scalar>],
    per_table_ts: &[Vec<E::Scalar>],
    per_table_T: &[Vec<E::Scalar>],
    r_logup_per_table: &[E::Scalar],
    transcript: &mut E::TE,
  ) -> Result<
    (
      Self,
      Vec<E::Scalar>,
      (
        E::Scalar,
        E::Scalar,
        E::Scalar,
        E::Scalar,
        E::Scalar,
        Vec<PerTableOuterEvals<E::Scalar>>,
      ),
    ),
    NovaError,
  > {
    let left = E1.len();
    let right = E2.len();
    let num_cons = left * right;
    let num_rounds_total = poly_Az.len().trailing_zeros() as usize;

    // Shape coherence — R1CS-side. Mirrors `prove_neutron_outer` at
    // `sumcheck.rs:571-578` byte-for-byte.
    assert_eq!(
      num_cons,
      poly_Az.len(),
      "prove_neutron_outer_with_logup: left*right must equal poly_Az.len() (== num_cons)",
    );
    assert_eq!(poly_Az.len(), poly_Bz.len());
    assert_eq!(poly_Az.len(), poly_Cz.len());
    assert!(left.is_power_of_two() && right.is_power_of_two());

    // Shape coherence — per-table (Finding F flat-embedding disposition).
    // All per-table polys live on the R1CS variable space at length `num_cons`.
    let k = r_logup_per_table.len();
    assert_eq!(
      per_table_eq_w.len(),
      k,
      "per_table_eq_w cardinality must equal k = r_logup_per_table.len()",
    );
    assert_eq!(per_table_eq_t.len(), k);
    assert_eq!(per_table_inv_w.len(), k);
    assert_eq!(per_table_inv_t.len(), k);
    assert_eq!(per_table_w.len(), k);
    assert_eq!(per_table_ts.len(), k);
    assert_eq!(per_table_T.len(), k);
    for j in 0..k {
      assert_eq!(
        per_table_eq_w[j].len(), num_cons,
        "per_table_eq_w[{}] must be pre-flattened to num_cons = {} (Corrigendum #16 Finding F)",
        j, num_cons,
      );
      assert_eq!(per_table_eq_t[j].len(), num_cons);
      assert_eq!(per_table_inv_w[j].len(), num_cons);
      assert_eq!(per_table_inv_t[j].len(), num_cons);
      assert_eq!(per_table_w[j].len(), num_cons);
      assert_eq!(per_table_ts[j].len(), num_cons);
      assert_eq!(per_table_T[j].len(), num_cons);
    }

    // Materialise `full_E` once at the start (Corrigendum #9 (3-A)). Same shape
    // as `prove_neutron_outer:585-594` byte-for-byte.
    let mut poly_E: MultilinearPolynomial<E::Scalar> = {
      let mut full_E: Vec<E::Scalar> = Vec::with_capacity(num_cons);
      for i in 0..right {
        for j in 0..left {
          full_E.push(E2[i] * E1[j]);
        }
      }
      debug_assert_eq!(full_E.len(), num_cons);
      MultilinearPolynomial::new(full_E)
    };

    // Wrap per-table polynomials in `MultilinearPolynomial` so we can apply
    // `bind_poly_var_top` per round in parallel with the R1CS-side polys.
    let mut polys_eq_w: Vec<MultilinearPolynomial<E::Scalar>> = per_table_eq_w
      .iter()
      .map(|v| MultilinearPolynomial::new(v.clone()))
      .collect();
    let mut polys_eq_t: Vec<MultilinearPolynomial<E::Scalar>> = per_table_eq_t
      .iter()
      .map(|v| MultilinearPolynomial::new(v.clone()))
      .collect();
    let mut polys_inv_w: Vec<MultilinearPolynomial<E::Scalar>> = per_table_inv_w
      .iter()
      .map(|v| MultilinearPolynomial::new(v.clone()))
      .collect();
    let mut polys_inv_t: Vec<MultilinearPolynomial<E::Scalar>> = per_table_inv_t
      .iter()
      .map(|v| MultilinearPolynomial::new(v.clone()))
      .collect();
    let mut polys_w: Vec<MultilinearPolynomial<E::Scalar>> = per_table_w
      .iter()
      .map(|v| MultilinearPolynomial::new(v.clone()))
      .collect();
    let mut polys_ts: Vec<MultilinearPolynomial<E::Scalar>> = per_table_ts
      .iter()
      .map(|v| MultilinearPolynomial::new(v.clone()))
      .collect();
    let mut polys_T: Vec<MultilinearPolynomial<E::Scalar>> = per_table_T
      .iter()
      .map(|v| MultilinearPolynomial::new(v.clone()))
      .collect();

    let mut r: Vec<E::Scalar> = Vec::with_capacity(num_rounds_total);
    let mut polys: Vec<CompressedUniPoly<E::Scalar>> = Vec::with_capacity(num_rounds_total);
    let mut claim_per_round = claim;

    for _round in 0..num_rounds_total {
      // Compute the per-round univariate `g_round(t)` of degree 3 under additive
      // composition. We evaluate at `{0, ∞, −1}` directly; `g(1)` is reconstructed
      // from the running claim via `g(1) = claim_per_round − g(0)` per the
      // BDDT-style sumcheck hint (mirrors `prove_neutron_outer:670-676`).
      //
      // After binding the top variable to `t`, each multilinear `P` is linear:
      //   P(t, x) = P_lo[x] + t · (P_hi[x] − P_lo[x])  =  P_lo[x] + t · dP[x]
      //
      // We exploit the additive structure: the per-round sum is
      //   g(t) = sum_x [ R1CS_body(t, x) + Σ_j A_body_j(t, x) + Σ_j B_body_j(t, x) ]
      // We sum over `x` inside the half-hypercube (`n = poly_Az.len() / 2`) in
      // parallel, accumulating (eval_0, leading, eval_neg1) per residue family.

      let n = poly_Az.len() / 2;
      debug_assert_eq!(n, poly_E.len() / 2);
      for j in 0..k {
        debug_assert_eq!(polys_eq_w[j].len() / 2, n);
        debug_assert_eq!(polys_eq_t[j].len() / 2, n);
        debug_assert_eq!(polys_inv_w[j].len() / 2, n);
        debug_assert_eq!(polys_inv_t[j].len() / 2, n);
        debug_assert_eq!(polys_w[j].len() / 2, n);
        debug_assert_eq!(polys_ts[j].len() / 2, n);
        debug_assert_eq!(polys_T[j].len() / 2, n);
      }

      // -----------------------------------------------------------------------
      // R1CS-side contribution — mirrors `prove_neutron_outer:625-668` exactly.
      // -----------------------------------------------------------------------
      let (r1cs_eval_0, r1cs_leading, r1cs_eval_neg1) = (0..n)
        .into_par_iter()
        .map(|i| {
          let a_lo = poly_Az[i];
          let b_lo = poly_Bz[i];
          let c_lo = poly_Cz[i];
          let e_lo = poly_E[i];

          let a_hi = poly_Az[n + i];
          let b_hi = poly_Bz[n + i];
          let c_hi = poly_Cz[n + i];
          let e_hi = poly_E[n + i];

          let g0 = e_lo * (a_lo * b_lo - c_lo);

          let d_a = a_hi - a_lo;
          let d_b = b_hi - b_lo;
          let d_e = e_hi - e_lo;
          let leading = d_e * d_a * d_b;

          let a_m1 = a_lo + a_lo - a_hi;
          let b_m1 = b_lo + b_lo - b_hi;
          let c_m1 = c_lo + c_lo - c_hi;
          let e_m1 = e_lo + e_lo - e_hi;
          let g_m1 = e_m1 * (a_m1 * b_m1 - c_m1);

          (g0, leading, g_m1)
        })
        .reduce(
          || (E::Scalar::ZERO, E::Scalar::ZERO, E::Scalar::ZERO),
          |a, b| (a.0 + b.0, a.1 + b.1, a.2 + b.2),
        );

      // -----------------------------------------------------------------------
      // Per-table (A) and (B) contributions — additive composition (Finding B).
      //
      // (A) per j: eq_w_j(t,x) · (inv_w_j(t,x) · (w_j(t,x) + r_logup_j) − 1)
      // (B) per j: eq_t_j(t,x) · (inv_t_j(t,x) · (T_j(t,x) + r_logup_j) − ts_j(t,x))
      //
      // Per-round degree-3 derivation (Finding C):
      //   eq · (inv · (poly + r) − const)
      //     = eq · (inv·poly + inv·r − const)
      // After binding to `t`, each base poly is degree-1 in `t`. The product
      // `inv(t)·poly(t)` is degree-2; `inv(t)·r` is degree-1; sum is degree-2;
      // minus a degree-1 (`ts_j` for (B)) or const-1 (for (A)) keeps it degree-2;
      // multiplied by `eq(t)` (degree-1) gives degree-3.
      //
      // Eval-point closed-form values:
      //   - g(0)   = eq_lo · (inv_lo·(poly_lo + r) − sub_lo)
      //   - g(−1): P(−1) = 2·P_lo − P_hi for every base poly P, then compose.
      //   - g(∞) = leading coefficient of t^3 in the expansion.
      //     The cubic-in-t expansion of eq(t)·(inv(t)·(poly(t)+r) − sub(t)) is
      //       eq(t)·inv(t)·poly(t)  −  eq(t)·(sub(t) − r·inv(t))
      //     The first term is degree 1×1×1=3, with leading coefficient
      //       d_eq · d_inv · d_poly
      //     The second term is degree 1×1=2 (NO t^3 contribution).
      //     For (A): `sub(t) − r·inv(t) = 1 − r·inv(t)` (sub is the constant 1);
      //     for (B): `sub(t) − r·inv(t) = ts(t) − r·inv(t)`. Both are degree ≤ 2.
      //   So `leading = d_eq · d_inv · d_poly` for both (A) and (B).
      // -----------------------------------------------------------------------
      let mut per_table_eval_0 = E::Scalar::ZERO;
      let mut per_table_leading = E::Scalar::ZERO;
      let mut per_table_eval_neg1 = E::Scalar::ZERO;

      for j in 0..k {
        let r_j = r_logup_per_table[j];

        // -------- (A) per j: eq_w_j · (inv_w_j · (w_j + r_j) − 1) -------------
        let (a_eval_0, a_leading, a_eval_neg1) = (0..n)
          .into_par_iter()
          .map(|i| {
            let eq_lo = polys_eq_w[j][i];
            let iw_lo = polys_inv_w[j][i];
            let w_lo = polys_w[j][i];

            let eq_hi = polys_eq_w[j][n + i];
            let iw_hi = polys_inv_w[j][n + i];
            let w_hi = polys_w[j][n + i];

            // g(0) = eq_lo · (iw_lo · (w_lo + r_j) − 1)
            let g0 = eq_lo * (iw_lo * (w_lo + r_j) - E::Scalar::ONE);

            // leading (g(∞)) = d_eq · d_iw · d_w
            let d_eq = eq_hi - eq_lo;
            let d_iw = iw_hi - iw_lo;
            let d_w = w_hi - w_lo;
            let leading = d_eq * d_iw * d_w;

            // g(−1): each P(−1) = 2·P_lo − P_hi
            let eq_m1 = eq_lo + eq_lo - eq_hi;
            let iw_m1 = iw_lo + iw_lo - iw_hi;
            let w_m1 = w_lo + w_lo - w_hi;
            let g_m1 = eq_m1 * (iw_m1 * (w_m1 + r_j) - E::Scalar::ONE);

            (g0, leading, g_m1)
          })
          .reduce(
            || (E::Scalar::ZERO, E::Scalar::ZERO, E::Scalar::ZERO),
            |a, b| (a.0 + b.0, a.1 + b.1, a.2 + b.2),
          );

        per_table_eval_0 += a_eval_0;
        per_table_leading += a_leading;
        per_table_eval_neg1 += a_eval_neg1;

        // -------- (B) per j: eq_t_j · (inv_t_j · (T_j + r_j) − ts_j) ----------
        let (b_eval_0, b_leading, b_eval_neg1) = (0..n)
          .into_par_iter()
          .map(|i| {
            let eq_lo = polys_eq_t[j][i];
            let it_lo = polys_inv_t[j][i];
            let T_lo = polys_T[j][i];
            let ts_lo = polys_ts[j][i];

            let eq_hi = polys_eq_t[j][n + i];
            let it_hi = polys_inv_t[j][n + i];
            let T_hi = polys_T[j][n + i];
            let ts_hi = polys_ts[j][n + i];

            // g(0) = eq_lo · (it_lo · (T_lo + r_j) − ts_lo)
            let g0 = eq_lo * (it_lo * (T_lo + r_j) - ts_lo);

            // leading (g(∞)) = d_eq · d_it · d_T
            let d_eq = eq_hi - eq_lo;
            let d_it = it_hi - it_lo;
            let d_T = T_hi - T_lo;
            let leading = d_eq * d_it * d_T;

            // g(−1)
            let eq_m1 = eq_lo + eq_lo - eq_hi;
            let it_m1 = it_lo + it_lo - it_hi;
            let T_m1 = T_lo + T_lo - T_hi;
            let ts_m1 = ts_lo + ts_lo - ts_hi;
            let g_m1 = eq_m1 * (it_m1 * (T_m1 + r_j) - ts_m1);

            (g0, leading, g_m1)
          })
          .reduce(
            || (E::Scalar::ZERO, E::Scalar::ZERO, E::Scalar::ZERO),
            |a, b| (a.0 + b.0, a.1 + b.1, a.2 + b.2),
          );

        per_table_eval_0 += b_eval_0;
        per_table_leading += b_leading;
        per_table_eval_neg1 += b_eval_neg1;
      }

      // -----------------------------------------------------------------------
      // Combine R1CS-side + per-table additive composition into the per-round
      // univariate (Finding B disposition: no gamma-RLC).
      // -----------------------------------------------------------------------
      let eval_0 = r1cs_eval_0 + per_table_eval_0;
      let leading_coeff = r1cs_leading + per_table_leading;
      let eval_neg1 = r1cs_eval_neg1 + per_table_eval_neg1;

      // Reconstruct g(1) from running claim per BDDT-style hint.
      let evals = vec![
        eval_0,
        claim_per_round - eval_0,
        leading_coeff,
        eval_neg1,
      ];
      let poly = UniPoly::from_evals_deg3(&evals);

      // Append prover's message; derive next-round challenge.
      transcript.absorb(b"p", &poly);
      let r_i = transcript.squeeze(b"c")?;
      r.push(r_i);
      polys.push(poly.compress());

      claim_per_round = poly.evaluate(&r_i);

      // Bind all polynomials at the top variable. R1CS-side bound in pairs via
      // `rayon::join` (mirrors `prove_neutron_outer:691-698`); per-table polys
      // bound sequentially per j (the per-j binds are independent so could be
      // parallelised, but the simpler sequential loop matches the engine-level
      // memory-access pattern of `lookup_sumcheck.rs:46-55`).
      rayon::join(
        || poly_Az.bind_poly_var_top(&r_i),
        || poly_Bz.bind_poly_var_top(&r_i),
      );
      rayon::join(
        || poly_Cz.bind_poly_var_top(&r_i),
        || poly_E.bind_poly_var_top(&r_i),
      );
      for j in 0..k {
        polys_eq_w[j].bind_poly_var_top(&r_i);
        polys_eq_t[j].bind_poly_var_top(&r_i);
        polys_inv_w[j].bind_poly_var_top(&r_i);
        polys_inv_t[j].bind_poly_var_top(&r_i);
        polys_w[j].bind_poly_var_top(&r_i);
        polys_ts[j].bind_poly_var_top(&r_i);
        polys_T[j].bind_poly_var_top(&r_i);
      }
    }

    // After `num_rounds_total = ell` rounds, all polynomials are reduced to a
    // single scalar each. Recover R1CS-side claims (mirrors
    // `prove_neutron_outer:703-705`).
    let claim_Az = poly_Az[0];
    let claim_Bz = poly_Bz[0];
    let claim_Cz = poly_Cz[0];

    // Reconstruct R1CS-side tensor factorisation at the verifier evaluation
    // point per Corrigendum #9 (2-A). Mirrors `prove_neutron_outer:711-716`.
    let ell2 = right.trailing_zeros() as usize;
    let r_x_high = &r[..ell2];
    let r_x_low = &r[ell2..];
    let eval_E1 = MultilinearPolynomial::new(E1.to_vec()).evaluate(r_x_low);
    let eval_E2 = MultilinearPolynomial::new(E2.to_vec()).evaluate(r_x_high);

    debug_assert_eq!(
      poly_E[0],
      eval_E1 * eval_E2,
      "Corrigendum #9 (2-A) tensor factorisation byte-divergence at end of \
       outer-sumcheck (with-logup path) — Falsifier D",
    );

    // Recover per-table evaluations at `r_x`. Each per-table poly was bound to
    // length-1 across the `num_rounds_total` rounds; the final value is `[0]`.
    let per_table_outer_evals: Vec<PerTableOuterEvals<E::Scalar>> = (0..k)
      .map(|j| PerTableOuterEvals {
        eval_w: polys_w[j][0],
        eval_ts: polys_ts[j][0],
        eval_inv_w: polys_inv_w[j][0],
        eval_inv_t: polys_inv_t[j][0],
        eval_T: polys_T[j][0],
        eval_eq_w: polys_eq_w[j][0],
        eval_eq_t: polys_eq_t[j][0],
      })
      .collect();

    Ok((
      SumcheckProof {
        compressed_polys: polys,
      },
      r,
      (
        claim_Az,
        claim_Bz,
        claim_Cz,
        eval_E1,
        eval_E2,
        per_table_outer_evals,
      ),
    ))
  }

  /// Prove sum_x eq(tau,x) * sum_i alpha_i * (A_i(x)*B_i(x) - C_i(x)) = claim
  /// for K instance triples sharing the same sumcheck structure.
  ///
  /// Returns (proof, r, claims) where `claims[i] = vec![A_i(r), B_i(r), C_i(r)]`.
  pub fn prove_batched_cubic(
    claim: &E::Scalar,
    taus: Vec<E::Scalar>,
    polys_A: &mut [MultilinearPolynomial<E::Scalar>],
    polys_B: &mut [MultilinearPolynomial<E::Scalar>],
    polys_C: &mut [MultilinearPolynomial<E::Scalar>],
    alphas: &[E::Scalar],
    transcript: &mut E::TE,
  ) -> Result<(Self, Vec<E::Scalar>, Vec<Vec<E::Scalar>>), NovaError> {
    let k = polys_A.len();
    if k == 0 {
      return Err(NovaError::InvalidNumInstances);
    }
    assert_eq!(k, polys_B.len());
    assert_eq!(k, polys_C.len());
    assert_eq!(k, alphas.len());

    let mut r: Vec<E::Scalar> = Vec::new();
    let mut polys: Vec<CompressedUniPoly<E::Scalar>> = Vec::new();
    let mut claim_per_round = *claim;

    let num_rounds = taus.len();
    let mut eq_instance = EqSumCheckInstance::<E>::new(taus);

    for _ in 0..num_rounds {
      let poly = {
        let (eval_point_0, eval_point_bound_coeff, eval_point_inf) = eq_instance
          .evaluation_points_batched_cubic(polys_A, polys_B, polys_C, alphas, claim_per_round);

        let evals = vec![
          eval_point_0,
          claim_per_round - eval_point_0,
          eval_point_bound_coeff,
          eval_point_inf,
        ];

        UniPoly::from_evals_deg3(&evals)
      };

      transcript.absorb(b"p", &poly);
      let r_i = transcript.squeeze(b"c")?;
      r.push(r_i);
      polys.push(poly.compress());
      claim_per_round = poly.evaluate(&r_i);

      polys_A
        .par_iter_mut()
        .chain(polys_B.par_iter_mut())
        .chain(polys_C.par_iter_mut())
        .for_each(|p| p.bind_poly_var_top(&r_i));
      eq_instance.bound(&r_i);
    }

    let claims: Vec<Vec<E::Scalar>> = (0..k)
      .map(|i| vec![polys_A[i][0], polys_B[i][0], polys_C[i][0]])
      .collect();

    Ok((
      SumcheckProof {
        compressed_polys: polys,
      },
      r,
      claims,
    ))
  }
}

pub mod eq_sumcheck {
  //! Sumcheck optimization for equality polynomials.
  //!
  //! The eq-factoring structure (splitting eq into left/right halves and evaluating at
  //! {0, inf, -1}) follows Gruen (eprint 2024/108, Section 3).
  //!
  //! The claim-derived evaluation points (computing only 2 N-scaling sums per round
  //! instead of 3) follow BDDT (eprint 2025/1117, Section 6.2).
  use crate::{spartan::polys::multilinear::MultilinearPolynomial, traits::Engine};
  use ff::Field;
  use rayon::{iter::ZipEq, prelude::*, slice::Iter};

  /// Instance for optimized equality polynomial sumcheck.
  pub struct EqSumCheckInstance<E: Engine> {
    // number of variables at first
    init_num_vars: usize,
    first_half: usize,
    second_half: usize,
    round: usize,
    taus: Vec<E::Scalar>,
    eval_eq_left: E::Scalar,
    poly_eq_left: Vec<Vec<E::Scalar>>,
    poly_eq_right: Vec<Vec<E::Scalar>>,
    eq_tau_0_a_inf: Vec<(E::Scalar, E::Scalar, E::Scalar)>,
  }

  impl<E: Engine> EqSumCheckInstance<E> {
    /// Creates a new EqSumCheckInstance from tau values.
    pub fn new(taus: Vec<E::Scalar>) -> Self {
      let l = taus.len();
      let first_half = l / 2;

      let compute_eq_polynomials = |taus: Vec<&E::Scalar>| -> Vec<Vec<E::Scalar>> {
        let len = taus.len();
        let mut result = Vec::with_capacity(len + 1);

        result.push(vec![E::Scalar::ONE]);

        for i in 0..len {
          let tau = taus[i];

          let prev = &result[i];
          let mut v_next = prev.to_vec();
          v_next.par_extend(prev.par_iter().map(|v| *v * tau));
          let (first, last) = v_next.split_at_mut(prev.len());
          first.par_iter_mut().zip(last).for_each(|(a, b)| *a -= *b);

          result.push(v_next);
        }

        result
      };

      let (left_taus, right_taus) = taus.split_at(first_half);
      let left_taus = left_taus.iter().skip(1).rev().collect::<Vec<_>>();
      let right_taus = right_taus.iter().rev().collect::<Vec<_>>();

      let (poly_eq_left, poly_eq_right) = rayon::join(
        || compute_eq_polynomials(left_taus),
        || compute_eq_polynomials(right_taus),
      );

      let eq_tau_0_a_inf = taus
        .par_iter()
        .map(|tau| {
          // eq(tau, 0), 2tau - 1, eq(tau, -1)
          let one_minus_tau = E::Scalar::ONE - tau;
          let two_tau_minus_one = *tau - one_minus_tau;
          let two_minus_three_tau = one_minus_tau - two_tau_minus_one;
          (one_minus_tau, two_tau_minus_one, two_minus_three_tau)
        })
        .collect::<Vec<_>>();

      Self {
        init_num_vars: l,
        first_half,
        second_half: l - first_half,
        round: 1,
        taus,
        eval_eq_left: E::Scalar::ONE,
        poly_eq_left,
        poly_eq_right,
        eq_tau_0_a_inf,
      }
    }

    // -----------------------------------------------------------------------
    // Claim-derived evaluation-point methods (BDDT, eprint 2025/1117 Section 6.2)
    //
    // These compute only 2 N-scaling sums (t(0) and t(inf)) instead of 3,
    // deriving s(-1) from the claim hint via O(1) work + 1 field inversion.
    // -----------------------------------------------------------------------

    /// O(1) derivation for a degree-2 inner polynomial.
    ///
    /// Given t(0) and t(inf) = leading coefficient of the inner polynomial t(X),
    /// plus the claim s(0)+s(1), derive (s(0), cubic_coeff(s), s(-1)).
    /// Returns `None` when tau=0 (l(1)=0), in which case the caller must
    /// compute the third N-scaling sum directly.
    #[inline]
    fn derive_from_claim_deg2(
      &self,
      t_0: E::Scalar,
      t_inf: E::Scalar,
      claim: E::Scalar,
    ) -> Option<(E::Scalar, E::Scalar, E::Scalar)> {
      let p = self.eval_eq_left;
      let (eq_0, eq_slope, eq_m1) = self.eq_tau_0_a_inf[self.round - 1];

      // l(X) = eq(tau_i, X) = eq_0 + eq_slope*X
      // l(0) = eq_0 = 1-tau,  l(1) = tau,  l(-1) = eq_m1 = 2-3*tau
      let l_0_p = eq_0 * p;
      let l_1_p = (eq_0 + eq_slope) * p; // tau * eval_eq_left

      // When tau=0, l(1)=0 so we can't invert -- fall back to 3-sum path
      let l_1_p_inv: Option<E::Scalar> = l_1_p.invert().into();
      let l_1_p_inv = l_1_p_inv?;

      // s(0) = l(0) * p * t(0)
      let s_0 = l_0_p * t_0;

      // s(1) = claim - s(0),  then t(1) = s(1) / (l(1) * p)
      let s_1 = claim - s_0;
      let t_1 = s_1 * l_1_p_inv;

      // cubic coefficient of s = eq_slope * p * t(inf)
      let s_leading = eq_slope * p * t_inf;

      // t(-1) = 2*t(inf) + 2*t(0) - t(1)   (since t is degree 2)
      let t_m1 = t_inf.double() + t_0.double() - t_1;

      // s(-1) = l(-1) * p * t(-1) = eq_m1 * p * t(-1)
      let s_m1 = eq_m1 * p * t_m1;

      Some((s_0, s_leading, s_m1))
    }

    /// O(1) derivation for a degree-1 inner polynomial (one-input case).
    /// Returns `None` when tau=0, in which case the caller must fall back.
    #[inline]
    fn derive_from_claim_deg1(
      &self,
      t_0: E::Scalar,
      claim: E::Scalar,
    ) -> Option<(E::Scalar, E::Scalar, E::Scalar)> {
      let p = self.eval_eq_left;
      let (eq_0, eq_slope, eq_m1) = self.eq_tau_0_a_inf[self.round - 1];

      let l_0_p = eq_0 * p;
      let l_1_p = (eq_0 + eq_slope) * p;

      let l_1_p_inv: Option<E::Scalar> = l_1_p.invert().into();
      let l_1_p_inv = l_1_p_inv?;

      let s_0 = l_0_p * t_0;
      let s_1 = claim - s_0;
      let t_1 = s_1 * l_1_p_inv;

      // s is degree 2 (linear l x linear t), so cubic coeff = 0
      let s_leading = E::Scalar::ZERO;

      // t(-1) = 2*t(0) - t(1)   (since t is degree 1)
      let t_m1 = t_0.double() - t_1;

      let s_m1 = eq_m1 * p * t_m1;

      Some((s_0, s_leading, s_m1))
    }

    /// Evaluate eq(tau,X) * sum_i alpha_i * (A_i*B_i - C_i) for K instance triples.
    ///
    /// Each triple (A_i, B_i, C_i) represents one R1CS instance. The inner
    /// polynomial t(X) = sum_i alpha_i * (A_i(X)*B_i(X) - C_i(X)) is still
    /// degree 2 in X, so BDDT claim derivation applies unchanged.
    #[inline]
    pub fn evaluation_points_batched_cubic(
      &self,
      polys_A: &[MultilinearPolynomial<E::Scalar>],
      polys_B: &[MultilinearPolynomial<E::Scalar>],
      polys_C: &[MultilinearPolynomial<E::Scalar>],
      alphas: &[E::Scalar],
      claim: E::Scalar,
    ) -> (E::Scalar, E::Scalar, E::Scalar) {
      let k = polys_A.len();
      assert!(k > 0);
      assert_eq!(k, polys_B.len());
      assert_eq!(k, polys_C.len());
      assert_eq!(k, alphas.len());
      assert_eq!(polys_A[0].len() % 2, 0);

      let in_first_half = self.round < self.first_half;
      let half_p = polys_A[0].Z.len() / 2;

      // Accumulate t(0) and t(inf) across all K instances
      let (t_0, t_inf) = if in_first_half {
        let (poly_eq_left, poly_eq_right, second_half, low_mask) = self.poly_eqs_first_half();

        (0..half_p)
          .into_par_iter()
          .map(|id| {
            let factor = poly_eq_left[id >> second_half] * poly_eq_right[id & low_mask];

            let mut sum_eval_0 = E::Scalar::ZERO;
            let mut sum_q = E::Scalar::ZERO;
            for i in 0..k {
              let zero_a = polys_A[i].Z[id];
              let one_a = polys_A[i].Z[id + half_p];
              let zero_b = polys_B[i].Z[id];
              let one_b = polys_B[i].Z[id + half_p];
              let zero_c = polys_C[i].Z[id];

              sum_eval_0 += alphas[i] * (zero_a * zero_b - zero_c);
              sum_q += alphas[i] * (one_a - zero_a) * (one_b - zero_b);
            }

            (sum_eval_0 * factor, sum_q * factor)
          })
          .reduce(
            || (E::Scalar::ZERO, E::Scalar::ZERO),
            |a, b| (a.0 + b.0, a.1 + b.1),
          )
      } else {
        let poly_eq_right = self.poly_eq_right_last_half();

        (0..half_p)
          .into_par_iter()
          .map(|id| {
            let eq_r = poly_eq_right[id];

            let mut sum_eval_0 = E::Scalar::ZERO;
            let mut sum_q = E::Scalar::ZERO;
            for i in 0..k {
              let zero_a = polys_A[i].Z[id];
              let one_a = polys_A[i].Z[id + half_p];
              let zero_b = polys_B[i].Z[id];
              let one_b = polys_B[i].Z[id + half_p];
              let zero_c = polys_C[i].Z[id];

              sum_eval_0 += alphas[i] * (zero_a * zero_b - zero_c);
              sum_q += alphas[i] * (one_a - zero_a) * (one_b - zero_b);
            }

            (sum_eval_0 * eq_r, sum_q * eq_r)
          })
          .reduce(
            || (E::Scalar::ZERO, E::Scalar::ZERO),
            |a, b| (a.0 + b.0, a.1 + b.1),
          )
      };

      if let Some(result) = self.derive_from_claim_deg2(t_0, t_inf, claim) {
        result
      } else {
        self.fallback_eval_inf_batched_cubic(t_0, t_inf, polys_A, polys_B, polys_C, alphas)
      }
    }

    /// Fallback for batched cubic: compute eval at -1 via third N-scaling sum.
    #[inline]
    fn fallback_eval_inf_batched_cubic(
      &self,
      t_0: E::Scalar,
      t_inf: E::Scalar,
      polys_A: &[MultilinearPolynomial<E::Scalar>],
      polys_B: &[MultilinearPolynomial<E::Scalar>],
      polys_C: &[MultilinearPolynomial<E::Scalar>],
      alphas: &[E::Scalar],
    ) -> (E::Scalar, E::Scalar, E::Scalar) {
      let p = self.eval_eq_left;
      let (eq_0, eq_slope, eq_m1) = self.eq_tau_0_a_inf[self.round - 1];
      let k = polys_A.len();
      let half_p = polys_A[0].Z.len() / 2;

      let s_0 = eq_0 * p * t_0;
      let s_leading = eq_slope * p * t_inf;

      let t_m1 = if self.round < self.first_half {
        let (poly_eq_left, poly_eq_right, second_half, low_mask) = self.poly_eqs_first_half();
        (0..half_p)
          .into_par_iter()
          .map(|id| {
            let factor = poly_eq_left[id >> second_half] * poly_eq_right[id & low_mask];

            let mut sum = E::Scalar::ZERO;
            for i in 0..k {
              let m1_a = polys_A[i].Z[id].double() - polys_A[i].Z[id + half_p];
              let m1_b = polys_B[i].Z[id].double() - polys_B[i].Z[id + half_p];
              let m1_c = polys_C[i].Z[id].double() - polys_C[i].Z[id + half_p];
              sum += alphas[i] * (m1_a * m1_b - m1_c);
            }
            sum * factor
          })
          .reduce(|| E::Scalar::ZERO, |a, b| a + b)
      } else {
        let poly_eq_right = self.poly_eq_right_last_half();
        (0..half_p)
          .into_par_iter()
          .map(|id| {
            let eq_r = poly_eq_right[id];

            let mut sum = E::Scalar::ZERO;
            for i in 0..k {
              let m1_a = polys_A[i].Z[id].double() - polys_A[i].Z[id + half_p];
              let m1_b = polys_B[i].Z[id].double() - polys_B[i].Z[id + half_p];
              let m1_c = polys_C[i].Z[id].double() - polys_C[i].Z[id + half_p];
              sum += alphas[i] * (m1_a * m1_b - m1_c);
            }
            sum * eq_r
          })
          .reduce(|| E::Scalar::ZERO, |a, b| a + b)
      };

      let s_m1 = eq_m1 * p * t_m1;
      (s_0, s_leading, s_m1)
    }

    /// Evaluate eq(tau,X) * (A*B - C) using 2 N-scaling sums instead of 3
    /// (BDDT, eprint 2025/1117 Section 6.2).
    /// Falls back to computing all 3 sums when tau=0 makes derivation impossible.
    #[inline]
    pub fn evaluation_points_cubic_with_three_inputs(
      &self,
      poly_A: &MultilinearPolynomial<E::Scalar>,
      poly_B: &MultilinearPolynomial<E::Scalar>,
      poly_C: &MultilinearPolynomial<E::Scalar>,
      claim: E::Scalar,
    ) -> (E::Scalar, E::Scalar, E::Scalar) {
      debug_assert_eq!(poly_A.len() % 2, 0);

      let in_first_half = self.round < self.first_half;
      let half_p = poly_A.Z.len() / 2;
      let [zip_A, zip_B, zip_C] = split_and_zip([&poly_A.Z, &poly_B.Z, &poly_C.Z], half_p);

      // Always compute t(0) and t(inf) (the quadratic coeff, i.e. product of deltas)
      let (t_0, t_inf) = if in_first_half {
        let (poly_eq_left, poly_eq_right, second_half, low_mask) = self.poly_eqs_first_half();

        zip_A
          .zip_eq(zip_B)
          .zip_eq(zip_C)
          .enumerate()
          .map(|(id, ((a, b), c))| {
            let (zero_a, one_a) = a;
            let (zero_b, one_b) = b;
            let (zero_c, _one_c) = c;

            let eval_0 = *zero_a * *zero_b - *zero_c;
            let q = (*one_a - *zero_a) * (*one_b - *zero_b);

            let factor = poly_eq_left[id >> second_half] * poly_eq_right[id & low_mask];

            (eval_0 * factor, q * factor)
          })
          .reduce(
            || (E::Scalar::ZERO, E::Scalar::ZERO),
            |a, b| (a.0 + b.0, a.1 + b.1),
          )
      } else {
        let poly_eq_right = self.poly_eq_right_last_half().par_iter();

        zip_A
          .zip_eq(zip_B)
          .zip_eq(zip_C)
          .zip_eq(poly_eq_right)
          .map(|(((a, b), c), eq_r)| {
            let (zero_a, one_a) = a;
            let (zero_b, one_b) = b;
            let (zero_c, _one_c) = c;

            let eval_0 = *zero_a * *zero_b - *zero_c;
            let q = (*one_a - *zero_a) * (*one_b - *zero_b);

            (eval_0 * eq_r, q * eq_r)
          })
          .reduce(
            || (E::Scalar::ZERO, E::Scalar::ZERO),
            |a, b| (a.0 + b.0, a.1 + b.1),
          )
      };

      // Try O(1) derivation from claim; fall back to computing eval_inf directly if tau=0
      if let Some(result) = self.derive_from_claim_deg2(t_0, t_inf, claim) {
        result
      } else {
        self.fallback_eval_inf_three_inputs(t_0, t_inf, poly_A, poly_B, poly_C)
      }
    }

    /// Evaluate eq(tau,X) * (A*B - 1) using 2 N-scaling sums instead of 3
    /// (BDDT, eprint 2025/1117 Section 6.2).
    /// Falls back to computing all 3 sums when tau=0.
    #[inline]
    pub fn evaluation_points_cubic_with_two_inputs(
      &self,
      poly_A: &MultilinearPolynomial<E::Scalar>,
      poly_B: &MultilinearPolynomial<E::Scalar>,
      claim: E::Scalar,
    ) -> (E::Scalar, E::Scalar, E::Scalar) {
      debug_assert_eq!(poly_A.len() % 2, 0);

      let in_first_half = self.round < self.first_half;
      let half_p = poly_A.Z.len() / 2;
      let [zip_A, zip_B] = split_and_zip([&poly_A.Z, &poly_B.Z], half_p);

      let (t_0, t_inf) = if in_first_half {
        let (poly_eq_left, poly_eq_right, second_half, low_mask) = self.poly_eqs_first_half();

        zip_A
          .zip_eq(zip_B)
          .enumerate()
          .map(|(id, (a, b))| {
            let (zero_a, one_a) = a;
            let (zero_b, one_b) = b;

            let one = E::Scalar::ONE;
            let eval_0 = *zero_a * *zero_b - one;
            let q = (*one_a - *zero_a) * (*one_b - *zero_b);

            let factor = poly_eq_left[id >> second_half] * poly_eq_right[id & low_mask];

            (eval_0 * factor, q * factor)
          })
          .reduce(
            || (E::Scalar::ZERO, E::Scalar::ZERO),
            |a, b| (a.0 + b.0, a.1 + b.1),
          )
      } else {
        let poly_eq_right = self.poly_eq_right_last_half().par_iter();

        zip_A
          .zip_eq(zip_B)
          .zip_eq(poly_eq_right)
          .map(|((a, b), eq_r)| {
            let (zero_a, one_a) = a;
            let (zero_b, one_b) = b;

            let one = E::Scalar::ONE;
            let eval_0 = *zero_a * *zero_b - one;
            let q = (*one_a - *zero_a) * (*one_b - *zero_b);

            (eval_0 * eq_r, q * eq_r)
          })
          .reduce(
            || (E::Scalar::ZERO, E::Scalar::ZERO),
            |a, b| (a.0 + b.0, a.1 + b.1),
          )
      };

      if let Some(result) = self.derive_from_claim_deg2(t_0, t_inf, claim) {
        result
      } else {
        self.fallback_eval_inf_two_inputs(t_0, t_inf, poly_A, poly_B)
      }
    }

    /// Evaluate eq(tau,X) * A using 1 N-scaling sum instead of 2
    /// (BDDT, eprint 2025/1117 Section 6.2).
    /// Falls back to computing both sums when tau=0.
    #[inline]
    pub fn evaluation_points_quadratic_with_one_input(
      &self,
      poly_A: &MultilinearPolynomial<E::Scalar>,
      claim: E::Scalar,
    ) -> (E::Scalar, E::Scalar, E::Scalar) {
      debug_assert_eq!(poly_A.len() % 2, 0);

      let in_first_half = self.round < self.first_half;
      let half_p = poly_A.Z.len() / 2;
      let [zip_A] = split_and_zip([&poly_A.Z], half_p);

      let t_0 = if in_first_half {
        let (poly_eq_left, poly_eq_right, second_half, low_mask) = self.poly_eqs_first_half();

        zip_A
          .enumerate()
          .map(|(id, a)| {
            let (zero_a, _one_a) = a;

            let factor = poly_eq_left[id >> second_half] * poly_eq_right[id & low_mask];

            *zero_a * factor
          })
          .reduce(|| E::Scalar::ZERO, |a, b| a + b)
      } else {
        let poly_eq_right = self.poly_eq_right_last_half().par_iter();

        zip_A
          .zip_eq(poly_eq_right)
          .map(|(a, eq_r)| {
            let (zero_a, _one_a) = a;
            *zero_a * eq_r
          })
          .reduce(|| E::Scalar::ZERO, |a, b| a + b)
      };

      if let Some(result) = self.derive_from_claim_deg1(t_0, claim) {
        result
      } else {
        self.fallback_eval_inf_one_input(t_0, poly_A)
      }
    }

    /// Fallback for three-input case: compute eval_inf via third N-scaling sum
    /// when claim-based derivation is impossible (tau=0).
    #[inline]
    fn fallback_eval_inf_three_inputs(
      &self,
      t_0: E::Scalar,
      t_inf: E::Scalar,
      poly_A: &MultilinearPolynomial<E::Scalar>,
      poly_B: &MultilinearPolynomial<E::Scalar>,
      poly_C: &MultilinearPolynomial<E::Scalar>,
    ) -> (E::Scalar, E::Scalar, E::Scalar) {
      let p = self.eval_eq_left;
      let (eq_0, eq_slope, eq_m1) = self.eq_tau_0_a_inf[self.round - 1];

      let s_0 = eq_0 * p * t_0;
      let s_leading = eq_slope * p * t_inf;

      // Compute eval at -1 via third N-scaling sum
      let half_p = poly_A.Z.len() / 2;
      let [zip_A, zip_B, zip_C] = split_and_zip([&poly_A.Z, &poly_B.Z, &poly_C.Z], half_p);

      let t_m1 = if self.round < self.first_half {
        let (poly_eq_left, poly_eq_right, second_half, low_mask) = self.poly_eqs_first_half();
        zip_A
          .zip_eq(zip_B)
          .zip_eq(zip_C)
          .enumerate()
          .map(|(id, ((a, b), c))| {
            let m1_a = a.0.double() - *a.1;
            let m1_b = b.0.double() - *b.1;
            let m1_c = c.0.double() - *c.1;
            let factor = poly_eq_left[id >> second_half] * poly_eq_right[id & low_mask];
            (m1_a * m1_b - m1_c) * factor
          })
          .reduce(|| E::Scalar::ZERO, |a, b| a + b)
      } else {
        let poly_eq_right = self.poly_eq_right_last_half().par_iter();
        zip_A
          .zip_eq(zip_B)
          .zip_eq(zip_C)
          .zip_eq(poly_eq_right)
          .map(|(((a, b), c), eq_r)| {
            let m1_a = a.0.double() - *a.1;
            let m1_b = b.0.double() - *b.1;
            let m1_c = c.0.double() - *c.1;
            (m1_a * m1_b - m1_c) * eq_r
          })
          .reduce(|| E::Scalar::ZERO, |a, b| a + b)
      };

      let s_m1 = eq_m1 * p * t_m1;
      (s_0, s_leading, s_m1)
    }

    /// Fallback for two-input case: compute eval_inf via third N-scaling sum.
    #[inline]
    fn fallback_eval_inf_two_inputs(
      &self,
      t_0: E::Scalar,
      t_inf: E::Scalar,
      poly_A: &MultilinearPolynomial<E::Scalar>,
      poly_B: &MultilinearPolynomial<E::Scalar>,
    ) -> (E::Scalar, E::Scalar, E::Scalar) {
      let p = self.eval_eq_left;
      let (eq_0, eq_slope, eq_m1) = self.eq_tau_0_a_inf[self.round - 1];

      let s_0 = eq_0 * p * t_0;
      let s_leading = eq_slope * p * t_inf;

      let half_p = poly_A.Z.len() / 2;
      let [zip_A, zip_B] = split_and_zip([&poly_A.Z, &poly_B.Z], half_p);

      let t_m1 = if self.round < self.first_half {
        let (poly_eq_left, poly_eq_right, second_half, low_mask) = self.poly_eqs_first_half();
        zip_A
          .zip_eq(zip_B)
          .enumerate()
          .map(|(id, (a, b))| {
            let m1_a = a.0.double() - *a.1;
            let m1_b = b.0.double() - *b.1;
            let factor = poly_eq_left[id >> second_half] * poly_eq_right[id & low_mask];
            (m1_a * m1_b - E::Scalar::ONE) * factor
          })
          .reduce(|| E::Scalar::ZERO, |a, b| a + b)
      } else {
        let poly_eq_right = self.poly_eq_right_last_half().par_iter();
        zip_A
          .zip_eq(zip_B)
          .zip_eq(poly_eq_right)
          .map(|((a, b), eq_r)| {
            let m1_a = a.0.double() - *a.1;
            let m1_b = b.0.double() - *b.1;
            (m1_a * m1_b - E::Scalar::ONE) * eq_r
          })
          .reduce(|| E::Scalar::ZERO, |a, b| a + b)
      };

      let s_m1 = eq_m1 * p * t_m1;
      (s_0, s_leading, s_m1)
    }

    /// Fallback for one-input case: compute eval_inf via second N-scaling sum.
    #[inline]
    fn fallback_eval_inf_one_input(
      &self,
      t_0: E::Scalar,
      poly_A: &MultilinearPolynomial<E::Scalar>,
    ) -> (E::Scalar, E::Scalar, E::Scalar) {
      let p = self.eval_eq_left;
      let (eq_0, _eq_slope, eq_m1) = self.eq_tau_0_a_inf[self.round - 1];

      let s_0 = eq_0 * p * t_0;
      let s_leading = E::Scalar::ZERO;

      let half_p = poly_A.Z.len() / 2;
      let [zip_A] = split_and_zip([&poly_A.Z], half_p);

      let t_m1 = if self.round < self.first_half {
        let (poly_eq_left, poly_eq_right, second_half, low_mask) = self.poly_eqs_first_half();
        zip_A
          .enumerate()
          .map(|(id, a)| {
            let m1_a = a.0.double() - *a.1;
            let factor = poly_eq_left[id >> second_half] * poly_eq_right[id & low_mask];
            m1_a * factor
          })
          .reduce(|| E::Scalar::ZERO, |a, b| a + b)
      } else {
        let poly_eq_right = self.poly_eq_right_last_half().par_iter();
        zip_A
          .zip_eq(poly_eq_right)
          .map(|(a, eq_r)| {
            let m1_a = a.0.double() - *a.1;
            m1_a * eq_r
          })
          .reduce(|| E::Scalar::ZERO, |a, b| a + b)
      };

      let s_m1 = eq_m1 * p * t_m1;
      (s_0, s_leading, s_m1)
    }

    /// Binds a variable in the sumcheck instance.
    #[inline]
    pub fn bound(&mut self, r: &E::Scalar) {
      let tau = self.taus[self.round - 1];
      self.eval_eq_left *= E::Scalar::ONE - tau - r + (*r * tau).double();
      self.round += 1;
    }

    #[inline]
    fn poly_eqs_first_half(&self) -> (&Vec<E::Scalar>, &Vec<E::Scalar>, usize, usize) {
      let second_half = self.second_half;
      let poly_eq_left = &self.poly_eq_left[self.first_half - self.round];
      let poly_eq_right = &self.poly_eq_right[second_half];

      debug_assert_eq!(poly_eq_right.len(), 1 << second_half);

      (
        poly_eq_left,
        poly_eq_right,
        second_half,
        (1 << second_half) - 1,
      )
    }

    #[inline]
    fn poly_eq_right_last_half(&self) -> &Vec<E::Scalar> {
      &self.poly_eq_right[self.init_num_vars - self.round]
    }
  }

  #[inline]
  fn split_and_zip<const N: usize, T: Sync>(
    vec: [&[T]; N],
    half_size: usize,
  ) -> [ZipEq<Iter<'_, T>, Iter<'_, T>>; N] {
    std::array::from_fn(|i| {
      let (left, right) = vec[i].split_at(half_size);
      left.par_iter().zip_eq(right.par_iter())
    })
  }
}
